import 'dotenv/config';
import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';

import habitsHandler from './api/habits.js';
import goalsHandler from './api/goals.js';
import trackingHandler from './api/tracking.js';
import dashboardHandler from './api/dashboard.js';
import reportsHandler from './api/reports.js';
import remindersHandler from './api/reminders.js';
import milestonesHandler from './api/milestones.js';
import achievementsHandler from './api/achievements.js';
import heatmapHandler from './api/heatmap.js';
import digestHandler from './api/digest.js';
import pushSubscribeHandler from './api/push-subscribe.js';
import pushSendHandler from './api/push-send.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = process.env.PORT || process.env.API_PORT || 3001;

app.use(express.json());

function wrap(handler) {
  return (req, res) => handler(req, res);
}

app.all('/api/habits',         wrap(habitsHandler));
app.all('/api/goals',          wrap(goalsHandler));
app.all('/api/tracking',       wrap(trackingHandler));
app.all('/api/dashboard',      wrap(dashboardHandler));
app.all('/api/reports',        wrap(reportsHandler));
app.all('/api/reminders',      wrap(remindersHandler));
app.all('/api/milestones',     wrap(milestonesHandler));
app.all('/api/achievements',   wrap(achievementsHandler));
app.all('/api/heatmap',        wrap(heatmapHandler));
app.all('/api/digest',         wrap(digestHandler));
app.all('/api/push-subscribe', wrap(pushSubscribeHandler));
app.all('/api/push-send',      wrap(pushSendHandler));

// Serve static assets generated by Vite build
app.use(express.static(path.join(__dirname, 'dist')));

// Fallback to index.html for React SPA routing
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'dist', 'index.html'));
});

app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
